import './global.css';
import { UiLayout } from '@/components/ui/ui-layout';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import {
  SolanaProvider,
  WalletButton,
} from '@/components/solana/solana-provider';
import { ReactQueryProvider } from './react-query-provider';
import { Yusei_Magic } from 'next/font/google';

const yusei = Yusei_Magic({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-yusei',
});

export const metadata = {
  title: 'views-app',
  description: 'Generated by create-solana-dapp',
};

const links: { label: string; path: string }[] = [
  { label: 'Account', path: '/account' },
  { label: 'Clusters', path: '/clusters' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${yusei.variable}`}>
      <body>
          <ReactQueryProvider>
            <ClusterProvider>
              <SolanaProvider>
                <UiLayout links={links}>{children}</UiLayout>
              </SolanaProvider>
            </ClusterProvider>
          </ReactQueryProvider>
      </body>
    </html>
  );
}
